name: Deploy
on: [push, workflow_dispatch]
jobs:
  cypress-run:
    name: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Create .env.local file
        run: echo MONGODB_URI=${{ secrets.TEST_MONGODB_URI }} >> .env.local
      - name: Create cypress.env.json
        run: echo "{\"mongodb\":{\"uri\":\"${{ secrets.TEST_MONGODB_URI }}\",\"database\":\"simple-cleaning-app\"}}" > cypress.env.json
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.5
        with:
          build: cat .env.local && yarn build
          start: cat .env.local && yarn start
  vercel-deploy:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Vercel Deploy
        uses: amondnet/vercel-action@v25.1.1
        with:
          github-comment: false
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: "--prod"
