name: Vercel Deploy
on: [push]
jobs:
  vercel-deploy:
    name: vercel-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Vercel Deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
